### ISSUE TITLE
Audio play in background not working in IOS. (expo-audio)

### ISSUE THREAD

**Issue by manjillama** [manjillama/audio-book-app#1]

**Comment by ibiams** [comment]
The expo documentation says:
[**This is not available in Expo client for iOS, it will only work in standalone apps**](https://docs.expo.io/versions/v39.0.0/sdk/audio/#arguments-1)

**Comment by manjillama** [comment]
Right! thank you for letting me know! Feel free to send PRs

**Comment by ibiams** [comment]
It would be nice! Do u have any suggestions on wha to do? @manjillama

**Comment by manjillama** [comment]
Not really but feel free to explore on your own. @ibiams
